// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/donation.proto


package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DonationIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationIdRequest) Reset() {
	*x = DonationIdRequest{}
	mi := &file_pb_donation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationIdRequest) ProtoMessage() {}

func (x *DonationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationIdRequest.ProtoReflect.Descriptor instead.
func (*DonationIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{0}
}

func (x *DonationIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DonationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationRequest) Reset() {
	*x = DonationRequest{}
	mi := &file_pb_donation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationRequest) ProtoMessage() {}

func (x *DonationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationRequest.ProtoReflect.Descriptor instead.
func (*DonationRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{1}
}

func (x *DonationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DonationRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DonationRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DonationRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DonationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DonationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DonationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,5,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	MessageText   string                 `protobuf:"bytes,7,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationResponse) Reset() {
	*x = DonationResponse{}
	mi := &file_pb_donation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationResponse) ProtoMessage() {}

func (x *DonationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationResponse.ProtoReflect.Descriptor instead.
func (*DonationResponse) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{2}
}

func (x *DonationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DonationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DonationResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DonationResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DonationResponse) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DonationResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DonationResponse) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *DonationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DonationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DonationResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Donation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Donation) Reset() {
	*x = Donation{}
	mi := &file_pb_donation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Donation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Donation) ProtoMessage() {}

func (x *Donation) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Donation.ProtoReflect.Descriptor instead.
func (*Donation) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{3}
}

func (x *Donation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Donation) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Donation) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *Donation) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Donation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Donation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Donation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Donation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetDonationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationsRequest) Reset() {
	*x = GetDonationsRequest{}
	mi := &file_pb_donation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationsRequest) ProtoMessage() {}

func (x *GetDonationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationsRequest.ProtoReflect.Descriptor instead.
func (*GetDonationsRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{4}
}

type GetDonationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Donations     []*Donation            `protobuf:"bytes,1,rep,name=donations,proto3" json:"donations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationsResponse) Reset() {
	*x = GetDonationsResponse{}
	mi := &file_pb_donation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationsResponse) ProtoMessage() {}

func (x *GetDonationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationsResponse.ProtoReflect.Descriptor instead.
func (*GetDonationsResponse) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{5}
}

func (x *GetDonationsResponse) GetDonations() []*Donation {
	if x != nil {
		return x.Donations
	}
	return nil
}

type TransactionIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionIdRequest) Reset() {
	*x = TransactionIdRequest{}
	mi := &file_pb_donation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionIdRequest) ProtoMessage() {}

func (x *TransactionIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionIdRequest.ProtoReflect.Descriptor instead.
func (*TransactionIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TransactionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DonationId         int32                  `protobuf:"varint,2,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
	InvoiceId          string                 `protobuf:"bytes,3,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	InvoiceUrl         string                 `protobuf:"bytes,4,opt,name=invoice_url,json=invoiceUrl,proto3" json:"invoice_url,omitempty"`
	InvoiceDescription string                 `protobuf:"bytes,5,opt,name=invoice_description,json=invoiceDescription,proto3" json:"invoice_description,omitempty"`
	PaymentMethod      string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount             float32                `protobuf:"fixed32,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_pb_donation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionRequest) GetDonationId() int32 {
	if x != nil {
		return x.DonationId
	}
	return 0
}

func (x *TransactionRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *TransactionRequest) GetInvoiceUrl() string {
	if x != nil {
		return x.InvoiceUrl
	}
	return ""
}

func (x *TransactionRequest) GetInvoiceDescription() string {
	if x != nil {
		return x.InvoiceDescription
	}
	return ""
}

func (x *TransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TransactionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Message            string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error              string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                 int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	DonationId         int32                  `protobuf:"varint,4,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
	InvoiceId          string                 `protobuf:"bytes,5,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	InvoiceUrl         string                 `protobuf:"bytes,6,opt,name=invoice_url,json=invoiceUrl,proto3" json:"invoice_url,omitempty"`
	InvoiceDescription string                 `protobuf:"bytes,7,opt,name=invoice_description,json=invoiceDescription,proto3" json:"invoice_description,omitempty"`
	PaymentMethod      string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount             float32                `protobuf:"fixed32,9,opt,name=amount,proto3" json:"amount,omitempty"`
	Status             string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_pb_donation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TransactionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponse) GetDonationId() int32 {
	if x != nil {
		return x.DonationId
	}
	return 0
}

func (x *TransactionResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *TransactionResponse) GetInvoiceUrl() string {
	if x != nil {
		return x.InvoiceUrl
	}
	return ""
}

func (x *TransactionResponse) GetInvoiceDescription() string {
	if x != nil {
		return x.InvoiceDescription
	}
	return ""
}

func (x *TransactionResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Transaction struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DonationId         int32                  `protobuf:"varint,2,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
	InvoiceId          string                 `protobuf:"bytes,3,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	InvoiceUrl         string                 `protobuf:"bytes,4,opt,name=invoice_url,json=invoiceUrl,proto3" json:"invoice_url,omitempty"`
	InvoiceDescription string                 `protobuf:"bytes,5,opt,name=invoice_description,json=invoiceDescription,proto3" json:"invoice_description,omitempty"`
	PaymentMethod      string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount             float32                `protobuf:"fixed32,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pb_donation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{9}
}

func (x *Transaction) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetDonationId() int32 {
	if x != nil {
		return x.DonationId
	}
	return 0
}

func (x *Transaction) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Transaction) GetInvoiceUrl() string {
	if x != nil {
		return x.InvoiceUrl
	}
	return ""
}

func (x *Transaction) GetInvoiceDescription() string {
	if x != nil {
		return x.InvoiceDescription
	}
	return ""
}

func (x *Transaction) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Transaction) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transaction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_pb_donation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{10}
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_pb_donation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_pb_donation_proto protoreflect.FileDescriptor

const file_pb_donation_proto_rawDesc = "" +
	"\n" +
	"\x11pb/donation.proto\x12\bdonation\"#\n" +
	"\x11DonationIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xa5\x01\n" +
	"\x0fDonationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\n" +
	"campaignId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x9b\x02\n" +
	"\x10DonationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcampaign_id\x18\x05 \x01(\x05R\n" +
	"campaignId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x02R\x06amount\x12!\n" +
	"\fmessage_text\x18\a \x01(\tR\vmessageText\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\n" +
	" \x01(\tR\tupdatedAt\"\xda\x01\n" +
	"\bDonation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\n" +
	"campaignId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\"\x15\n" +
	"\x13GetDonationsRequest\"H\n" +
	"\x14GetDonationsResponse\x120\n" +
	"\tdonations\x18\x01 \x03(\v2\x12.donation.DonationR\tdonations\"&\n" +
	"\x14TransactionIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x8d\x02\n" +
	"\x12TransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vdonation_id\x18\x02 \x01(\x05R\n" +
	"donationId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x03 \x01(\tR\tinvoiceId\x12\x1f\n" +
	"\vinvoice_url\x18\x04 \x01(\tR\n" +
	"invoiceUrl\x12/\n" +
	"\x13invoice_description\x18\x05 \x01(\tR\x12invoiceDescription\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\a \x01(\x02R\x06amount\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\xfc\x02\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x1f\n" +
	"\vdonation_id\x18\x04 \x01(\x05R\n" +
	"donationId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x05 \x01(\tR\tinvoiceId\x12\x1f\n" +
	"\vinvoice_url\x18\x06 \x01(\tR\n" +
	"invoiceUrl\x12/\n" +
	"\x13invoice_description\x18\a \x01(\tR\x12invoiceDescription\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\t \x01(\x02R\x06amount\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xc4\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vdonation_id\x18\x02 \x01(\x05R\n" +
	"donationId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x03 \x01(\tR\tinvoiceId\x12\x1f\n" +
	"\vinvoice_url\x18\x04 \x01(\tR\n" +
	"invoiceUrl\x12/\n" +
	"\x13invoice_description\x18\x05 \x01(\tR\x12invoiceDescription\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\a \x01(\x02R\x06amount\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x18\n" +
	"\x16GetTransactionsRequest\"T\n" +
	"\x17GetTransactionsResponse\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.donation.TransactionR\ftransactions2\xe7\x05\n" +
	"\x0fDonationService\x12J\n" +
	"\x0fGetDonationByID\x12\x1b.donation.DonationIdRequest\x1a\x1a.donation.DonationResponse\x12P\n" +
	"\x0fGetAllDonations\x12\x1d.donation.GetDonationsRequest\x1a\x1e.donation.GetDonationsResponse\x12G\n" +
	"\x0eCreateDonation\x12\x19.donation.DonationRequest\x1a\x1a.donation.DonationResponse\x12G\n" +
	"\x0eUpdateDonation\x12\x19.donation.DonationRequest\x1a\x1a.donation.DonationResponse\x12S\n" +
	"\x12GetTransactionByID\x12\x1e.donation.TransactionIdRequest\x1a\x1d.donation.TransactionResponse\x12Y\n" +
	"\x12GetAllTransactions\x12 .donation.GetTransactionsRequest\x1a!.donation.GetTransactionsResponse\x12P\n" +
	"\x11CreateTransaction\x12\x1c.donation.TransactionRequest\x1a\x1d.donation.TransactionResponse\x12P\n" +
	"\x11UpdateTransaction\x12\x1c.donation.TransactionRequest\x1a\x1d.donation.TransactionResponse\x12P\n" +
	"\x0fSyncTransaction\x12\x1e.donation.TransactionIdRequest\x1a\x1d.donation.TransactionResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_pb_donation_proto_rawDescOnce sync.Once
	file_pb_donation_proto_rawDescData []byte
)

func file_pb_donation_proto_rawDescGZIP() []byte {
	file_pb_donation_proto_rawDescOnce.Do(func() {
		file_pb_donation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_donation_proto_rawDesc), len(file_pb_donation_proto_rawDesc)))
	})
	return file_pb_donation_proto_rawDescData
}

var file_pb_donation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_donation_proto_goTypes = []any{
	(*DonationIdRequest)(nil),       // 0: donation.DonationIdRequest
	(*DonationRequest)(nil),         // 1: donation.DonationRequest
	(*DonationResponse)(nil),        // 2: donation.DonationResponse
	(*Donation)(nil),                // 3: donation.Donation
	(*GetDonationsRequest)(nil),     // 4: donation.GetDonationsRequest
	(*GetDonationsResponse)(nil),    // 5: donation.GetDonationsResponse
	(*TransactionIdRequest)(nil),    // 6: donation.TransactionIdRequest
	(*TransactionRequest)(nil),      // 7: donation.TransactionRequest
	(*TransactionResponse)(nil),     // 8: donation.TransactionResponse
	(*Transaction)(nil),             // 9: donation.Transaction
	(*GetTransactionsRequest)(nil),  // 10: donation.GetTransactionsRequest
	(*GetTransactionsResponse)(nil), // 11: donation.GetTransactionsResponse
}
var file_pb_donation_proto_depIdxs = []int32{
	3,  // 0: donation.GetDonationsResponse.donations:type_name -> donation.Donation
	9,  // 1: donation.GetTransactionsResponse.transactions:type_name -> donation.Transaction
	0,  // 2: donation.DonationService.GetDonationByID:input_type -> donation.DonationIdRequest
	4,  // 3: donation.DonationService.GetAllDonations:input_type -> donation.GetDonationsRequest
	1,  // 4: donation.DonationService.CreateDonation:input_type -> donation.DonationRequest
	1,  // 5: donation.DonationService.UpdateDonation:input_type -> donation.DonationRequest
	6,  // 6: donation.DonationService.GetTransactionByID:input_type -> donation.TransactionIdRequest
	10, // 7: donation.DonationService.GetAllTransactions:input_type -> donation.GetTransactionsRequest
	7,  // 8: donation.DonationService.CreateTransaction:input_type -> donation.TransactionRequest
	7,  // 9: donation.DonationService.UpdateTransaction:input_type -> donation.TransactionRequest
	6,  // 10: donation.DonationService.SyncTransaction:input_type -> donation.TransactionIdRequest
	2,  // 11: donation.DonationService.GetDonationByID:output_type -> donation.DonationResponse
	5,  // 12: donation.DonationService.GetAllDonations:output_type -> donation.GetDonationsResponse
	2,  // 13: donation.DonationService.CreateDonation:output_type -> donation.DonationResponse
	2,  // 14: donation.DonationService.UpdateDonation:output_type -> donation.DonationResponse
	8,  // 15: donation.DonationService.GetTransactionByID:output_type -> donation.TransactionResponse
	11, // 16: donation.DonationService.GetAllTransactions:output_type -> donation.GetTransactionsResponse
	8,  // 17: donation.DonationService.CreateTransaction:output_type -> donation.TransactionResponse
	8,  // 18: donation.DonationService.UpdateTransaction:output_type -> donation.TransactionResponse
	8,  // 19: donation.DonationService.SyncTransaction:output_type -> donation.TransactionResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pb_donation_proto_init() }
func file_pb_donation_proto_init() {
	if File_pb_donation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_donation_proto_rawDesc), len(file_pb_donation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_donation_proto_goTypes,
		DependencyIndexes: file_pb_donation_proto_depIdxs,
		MessageInfos:      file_pb_donation_proto_msgTypes,
	}.Build()
	File_pb_donation_proto = out.File
	file_pb_donation_proto_goTypes = nil
	file_pb_donation_proto_depIdxs = nil
}
