// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/donation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DonationIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationIdRequest) Reset() {
	*x = DonationIdRequest{}
	mi := &file_pb_donation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationIdRequest) ProtoMessage() {}

func (x *DonationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationIdRequest.ProtoReflect.Descriptor instead.
func (*DonationIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{0}
}

func (x *DonationIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DonationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationRequest) Reset() {
	*x = DonationRequest{}
	mi := &file_pb_donation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationRequest) ProtoMessage() {}

func (x *DonationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationRequest.ProtoReflect.Descriptor instead.
func (*DonationRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{1}
}

func (x *DonationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DonationRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DonationRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DonationRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DonationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DonationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DonationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationResponse) Reset() {
	*x = DonationResponse{}
	mi := &file_pb_donation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationResponse) ProtoMessage() {}

func (x *DonationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationResponse.ProtoReflect.Descriptor instead.
func (*DonationResponse) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{2}
}

func (x *DonationResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DonationResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DonationResponse) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DonationResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DonationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DonationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DonationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DonationResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Donation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Donation) Reset() {
	*x = Donation{}
	mi := &file_pb_donation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Donation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Donation) ProtoMessage() {}

func (x *Donation) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Donation.ProtoReflect.Descriptor instead.
func (*Donation) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{3}
}

func (x *Donation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Donation) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Donation) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *Donation) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Donation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Donation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Donation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Donation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetDonationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationsRequest) Reset() {
	*x = GetDonationsRequest{}
	mi := &file_pb_donation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationsRequest) ProtoMessage() {}

func (x *GetDonationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationsRequest.ProtoReflect.Descriptor instead.
func (*GetDonationsRequest) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{4}
}

type GetDonationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Donations     []*Donation            `protobuf:"bytes,1,rep,name=donations,proto3" json:"donations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationsResponse) Reset() {
	*x = GetDonationsResponse{}
	mi := &file_pb_donation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationsResponse) ProtoMessage() {}

func (x *GetDonationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_donation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationsResponse.ProtoReflect.Descriptor instead.
func (*GetDonationsResponse) Descriptor() ([]byte, []int) {
	return file_pb_donation_proto_rawDescGZIP(), []int{5}
}

func (x *GetDonationsResponse) GetDonations() []*Donation {
	if x != nil {
		return x.Donations
	}
	return nil
}

var File_pb_donation_proto protoreflect.FileDescriptor

const file_pb_donation_proto_rawDesc = "" +
	"\n" +
	"\x11pb/donation.proto\x12\bdonation\"#\n" +
	"\x11DonationIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa5\x01\n" +
	"\x0fDonationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\n" +
	"campaignId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xe2\x01\n" +
	"\x10DonationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\n" +
	"campaignId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\"\xda\x01\n" +
	"\bDonation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\n" +
	"campaignId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\"\x15\n" +
	"\x13GetDonationsRequest\"H\n" +
	"\x14GetDonationsResponse\x120\n" +
	"\tdonations\x18\x01 \x03(\v2\x12.donation.DonationR\tdonations2\xc1\x02\n" +
	"\x0fDonationService\x12J\n" +
	"\x0fGetDonationByID\x12\x1b.donation.DonationIdRequest\x1a\x1a.donation.DonationResponse\x12P\n" +
	"\x0fGetAllDonations\x12\x1d.donation.GetDonationsRequest\x1a\x1e.donation.GetDonationsResponse\x12G\n" +
	"\x0eCreateDonation\x12\x19.donation.DonationRequest\x1a\x1a.donation.DonationResponse\x12G\n" +
	"\x0eUpdateDonation\x12\x19.donation.DonationRequest\x1a\x1a.donation.DonationResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_pb_donation_proto_rawDescOnce sync.Once
	file_pb_donation_proto_rawDescData []byte
)

func file_pb_donation_proto_rawDescGZIP() []byte {
	file_pb_donation_proto_rawDescOnce.Do(func() {
		file_pb_donation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_donation_proto_rawDesc), len(file_pb_donation_proto_rawDesc)))
	})
	return file_pb_donation_proto_rawDescData
}

var file_pb_donation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_donation_proto_goTypes = []any{
	(*DonationIdRequest)(nil),    // 0: donation.DonationIdRequest
	(*DonationRequest)(nil),      // 1: donation.DonationRequest
	(*DonationResponse)(nil),     // 2: donation.DonationResponse
	(*Donation)(nil),             // 3: donation.Donation
	(*GetDonationsRequest)(nil),  // 4: donation.GetDonationsRequest
	(*GetDonationsResponse)(nil), // 5: donation.GetDonationsResponse
}
var file_pb_donation_proto_depIdxs = []int32{
	3, // 0: donation.GetDonationsResponse.donations:type_name -> donation.Donation
	0, // 1: donation.DonationService.GetDonationByID:input_type -> donation.DonationIdRequest
	4, // 2: donation.DonationService.GetAllDonations:input_type -> donation.GetDonationsRequest
	1, // 3: donation.DonationService.CreateDonation:input_type -> donation.DonationRequest
	1, // 4: donation.DonationService.UpdateDonation:input_type -> donation.DonationRequest
	2, // 5: donation.DonationService.GetDonationByID:output_type -> donation.DonationResponse
	5, // 6: donation.DonationService.GetAllDonations:output_type -> donation.GetDonationsResponse
	2, // 7: donation.DonationService.CreateDonation:output_type -> donation.DonationResponse
	2, // 8: donation.DonationService.UpdateDonation:output_type -> donation.DonationResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_donation_proto_init() }
func file_pb_donation_proto_init() {
	if File_pb_donation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_donation_proto_rawDesc), len(file_pb_donation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_donation_proto_goTypes,
		DependencyIndexes: file_pb_donation_proto_depIdxs,
		MessageInfos:      file_pb_donation_proto_msgTypes,
	}.Build()
	File_pb_donation_proto = out.File
	file_pb_donation_proto_goTypes = nil
	file_pb_donation_proto_depIdxs = nil
}
